# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

- hosts: localhost

  vars:
   resouce_group: __resourceGroupName__
   location: __location__
   webapp_name: __webappName__
   mysqlsever_name: __mysqlServerName__
   mysqldb_name: __mysqlDbName__
   admin_username: __mysqlAdmin__
   admin_password: __mysqlAdminSecret__
   
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
        
    - name: Create App Service on Windows with Java Runtime
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp_name }}"
        plan:
          resource_group: "{{ resouce_group }}"
          name: myappplan
          is_linux: false
          sku: S1
          number_of_workers: 1
         frameworks:
          - name: "java"
            version: "1.8"
            settings:
              java_container: tomcat
              java_container_version: 9.0

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.14', 'vs2017-win2016'


steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
